# AI Assisted System for Prioritizing Government Contracts for Human Review

**Name:** `Arriyan Ali`  
**SFU ID:** `301473637`  
**Date:** `8/5/2026`

---

## Setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib.backends.registry'

In [ ]:
df = pd.read_csv('load-contracts-2020-10-01.csv')

## EDA

In [4]:
df.head()

,reference_number,procurement_id,vendor_name,vendor_postal_code,buyer_name,contract_date,economic_object_code,description_en,description_fr,contract_period_start,...,number_of_bids,article_6_exceptions,award_criteria,socioeconomic_indicator,reporting_period,record_created,record_modified,user_modified,owner_org,owner_org_title
0,C-2018-2019-Q1-00069,4500377604,CANADIAN CORPS OF COMMISSIONAIRES,NaN,NaN,2018-04-01,460,Protection services,Services de protection,2018-04-01,...,NaN,NaN,NaN,NaN,C,NaN,NaN,*,aandc-aadnc,NaN
1,C-2018-2019-Q1-00160,4500379911,ADLAIR AVIATION (1983) LTD,NaN,NaN,2018-05-28,533,"Rental of machinery, office furniture and fixt...","Location de machinerie, de mobilier et d'insta...",2018-05-28,...,NaN,NaN,NaN,NaN,C,NaN,NaN,*,aandc-aadnc,NaN
2,C-2018-2019-Q1-00147,4500379558,7260491 CANADA INC. KMOTIONS,NaN,NaN,2018-06-05,351,Communication Services,Services de communication,2018-06-11,...,NaN,NaN,NaN,NaN,C,NaN,NaN,*,aandc-aadnc,NaN
3,C-2018-2019-Q1-00246,4500381745,8199400 CANADA INC. (SUMMIT AIR),NaN,NaN,2018-06-25,561,Rental of aircraft,Location d'aéronefs,2018-06-25,...,NaN,NaN,NaN,NaN,C,NaN,NaN,*,aandc-aadnc,NaN
4,C-2018-2019-Q1-00234,4500381514,AIR TINDI LTD,NaN,NaN,2018-06-19,561,Rental of aircraft,Location d'aéronefs,2018-06-19,...,NaN,NaN,NaN,NaN,C,NaN,NaN,*,aandc-aadnc,NaN

In [7]:
# Checking missing values
df.isnull().sum()

reference_number                        0
procurement_id                          5
vendor_name                             0
vendor_postal_code                   2470
buyer_name                           2470
contract_date                           0
economic_object_code                  407
description_en                        356
description_fr                        358
contract_period_start                   0
delivery_date                           1
contract_value                          0
original_value                         12
amendment_value                       188
comments_en                          1161
comments_fr                          1119
additional_comments_en               2087
additional_comments_fr               2137
agreement_type_code                   819
trade_agreement                      2470
land_claims                          2470
commodity_type                         51
commodity_code                        415
country_of_vendor                      59
solicitation_procedure                 10
limited_tendering_reason             1011
trade_agreement_exceptions            158
aboriginal_business                  2470
aboriginal_business_incidental         51
intellectual_property                 140
potential_commercial_exploitation     613
former_public_servant                 181
contracting_entity                   1123
standing_offer_number                 872
instrument_type                        78
ministers_office                     2334
number_of_bids                       2470
article_6_exceptions                 2470
award_criteria                       2470
socioeconomic_indicator              2470
reporting_period                      375
record_created                       2470
record_modified                      2470
user_modified                           0
owner_org                               0
owner_org_title                      2470
dtype: int64

#### 1) EDA Analysis

**Core columns**

The main values I need for the first half of the problem I need to solve have no missing values which is good news.

contract_value has 0 missing. This will ve my main numeric signal

contract_date and contract_period_start also has 0 missing, these will help me find timing or date based correalations

vendor_name and owner_org have 0 missing as well so the supplier and department info is good

<br>

**Empty columns**

vendor_postal_code

buyer_name

trade_agreement

land_claims

aboriginal_bisiness

number_of_bids

article_6_exceptions

award_criteria

socioeconomic_indicator

record_created

record_modified

owner_org_title

<br>

**Partially Missing**

amendment_value has 188 missing, which should be gine since contracts that were never amended wouldnt have a value. I think it would be better to replace these with a 0 valie than treate them as missing.

limited_tendering_reason has 1011 missing, standing_offer_number has 872 missing, and contracting_entity has 1123 missing. These seem like fields that only apply to certain procurement types. Them being missing could be useful information instead of noise to be cleaned(ex. was this competitively bid at all?) 

ministers_office has 2334 missing, meaning only 136 contracts have anything for this. I might keep this as a binary indicator instead of just dropping it outright.

## Progress Report